# Packages one hole from the golf-sim-oc project into hole-viewer/holeNN-data.js
# so the Quarto page can embed it (embed-resources only inlines files that are
# referenced by <script src>, not files fetched at runtime).
#
# Usage (from this folder):
#   powershell -ExecutionPolicy Bypass -File build-hole-data.ps1 -Hole 7
param(
  [int]$Hole = 7,
  [string]$SimDir = "$env:USERPROFILE\OneDrive\Desktop\golf-sim-oc",
  [double]$ImageScale = 0.5,   # shrink the aerial photo to keep the page small
  [int]$JpegQuality = 82
)

$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing

$nn = '{0:D2}' -f $Hole
$data = Join-Path $SimDir 'CourseData'
$out = Join-Path $PSScriptRoot "hole$nn-data.js"

# ---- aerial photo, resized ----
$src = [System.Drawing.Image]::FromFile((Join-Path $data "terrain$nn.jpg"))
try {
  $w = [int]($src.Width * $ImageScale); $h = [int]($src.Height * $ImageScale)
  $bmp = New-Object System.Drawing.Bitmap $w, $h
  $g = [System.Drawing.Graphics]::FromImage($bmp)
  $g.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
  $g.DrawImage($src, 0, 0, $w, $h)
  $g.Dispose()
  $codec = [System.Drawing.Imaging.ImageCodecInfo]::GetImageEncoders() | Where-Object { $_.MimeType -eq 'image/jpeg' }
  $params = New-Object System.Drawing.Imaging.EncoderParameters 1
  $params.Param[0] = New-Object System.Drawing.Imaging.EncoderParameter ([System.Drawing.Imaging.Encoder]::Quality), ([long]$JpegQuality)
  $ms = New-Object System.IO.MemoryStream
  $bmp.Save($ms, $codec, $params)
  $bmp.Dispose()
  $jpgB64 = [Convert]::ToBase64String($ms.ToArray())
} finally { $src.Dispose() }

# ---- meshes ----
$terrainB64 = [Convert]::ToBase64String([IO.File]::ReadAllBytes((Join-Path $data "terrain$nn.glb")))
$greenB64 = [Convert]::ToBase64String([IO.File]::ReadAllBytes((Join-Path $data "Green$nn.glb")))

# ---- metadata ----
$tfw = (Get-Content (Join-Path $data "terrain$nn.tfw.txt") | Where-Object { $_.Trim() } | ForEach-Object { [double]$_ })
$tournament = Get-Content (Join-Path $data 'tournament_data.json') -Raw | ConvertFrom-Json
$holeInfo = $tournament.holes | Where-Object { $_.number -eq $Hole }
$calib = (Get-Content (Join-Path $data 'green_calibration.json') -Raw | ConvertFrom-Json)."$Hole"

$pins = @{}
if ($calib -and $calib.pinPositions) {
  foreach ($p in $calib.pinPositions.PSObject.Properties) {
    $pins[$p.Name] = @{ x = $p.Value.x; z = $p.Value.z }
  }
}

$meta = [ordered]@{
  hole    = $Hole
  course  = 'Pebble Beach Golf Links'
  par     = $holeInfo.par
  yardage = $holeInfo.yardage
  tfw     = $tfw
  pins    = $pins
} | ConvertTo-Json -Depth 5 -Compress

$js = "// Generated by build-hole-data.ps1 - do not edit.`n" +
  "window.HOLE_VIEWER_DATA = Object.assign($meta, {`n" +
  "  terrainGlb: `"$terrainB64`",`n" +
  "  greenGlb: `"$greenB64`",`n" +
  "  aerialJpg: `"$jpgB64`"`n" +
  "});`n"
[IO.File]::WriteAllText($out, $js, (New-Object System.Text.UTF8Encoding $false))

'{0} written ({1:N1} MB)' -f $out, ((Get-Item $out).Length / 1MB)
