project:
  type: website
  output-dir: docs

website:
  title: "Home"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: "AFL"
        menu:
          - text: "Model"
            href: http://rexcarruthers.github.io/Website/AFLMod
          - text: "Brownlow Model"
            href: https://rexcarruthers.github.io/Website/BLModel/
          - text: "2025 Sim Shiny App"
            href: https://rexapps.shinyapps.io/AFLSim2026/
          - text: "Boids"
            href: https://rexcarruthers.github.io/Website/Boids/
      - text: "Golf"
        menu:
          - text: "Overview"
            href: http://rexcarruthers.github.io/Website/AFLMod
          - text: "Overview"
            href: http://rexcarruthers.github.io/Website/AFLMod
          - text: "Overview"
            href: http://rexcarruthers.github.io/Website/AFLMod
          - text: "Overview"
            href: http://rexcarruthers.github.io/Website/AFLMod
        target: _blank
      - text: Projects
        href: projects/index.qmd
      
format:
  html:
    link-external-newwindow: true
    theme:
      light: [cosmo, styles.scss]
      dark: [cosmo, styles-dark.scss]

